# Generated by Django 3.1.2 on 2021-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOING', 'DOING'), ('DONE', 'DONE')], default='PENDING', max_length=255, verbose_name='Status'),
        ),
    ]
