# Generated by Django 3.1.2 on 2021-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_photos', verbose_name='Family photo'),
        ),
        migrations.AddField(
            model_name='family',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
    ]
